apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spark-master
  namespace: {{K8S_NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: spark-master
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: spark-master
    spec:
      containers:
        - name: spark-master
          image: stratospire/spark:2.0.0
          command: ["/start-master"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
